name: Teste de ci/cd

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache_step
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/{package-lock.json,*.lock}') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install
        if: steps.cache_step.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        run: npm run lint
        if: success()

      - name: Format
        run: npm run format
        if: success()

      - name: Build
        run: npm run build
        if: success()

      - name: Deploy
        if: github.event_name == 'pull_request'
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=./out
